export const ROUTES = {
    home: '',
    login: 'auth/login',
    signup: 'auth/sign-up',
    profileDetail: 'auth/detail/:id',
    profileCourses: 'auth/courses/:id',
    listCourses: 'learning',
    infoCourse: 'learning/:reg',
    learningCourse: 'learning/:reg/study',
    examList: 'exam-list',
    doExam: 'do-exam/:reg',
    quiz: 'quiz-list',
    doQuiz: 'do-quiz/:reg',
    about: 'about',
    setting: 'setting',
    notfound: '*',
};

export const PATH = {
    home: '/' + ROUTES.home,
    login: '/' + ROUTES.login,
    signup: '/' + ROUTES.signup,
    profileDetail: '/' + ROUTES.profileDetail,
    profileCourses: '/' + ROUTES.profileCourses,
    listCourses: '/' + ROUTES.listCourses,
    infoCourse: '/' + ROUTES.infoCourse,
    learningCourse: '/' + ROUTES.learningCourse,
    examList: '/' + ROUTES.examList,
    doExam: '/' + ROUTES.doExam,
    quiz: '/' + ROUTES.quiz,
    doQuiz: '/' + ROUTES.doQuiz,
    about: '/' + ROUTES.about,
    setting: '/' + ROUTES.setting,
    notfound: '/' + ROUTES.notfound,
};
